### ISSUE TITLE
Allow user to choose in which chain/token they want to pay.

### ISSUE THREAD

**Issue by LefterisJP** [3cities/3cities#151]
As detailed here: https://x.com/LefterisJP/status/1813154377579839584 it's impossible for a user to figure out how they can pay.

It's impossible for a user to find out what tokens or chains they can pay in. Ligi pointed out here: https://x.com/mr_ligi/status/1813178235468808455 that the payment processing software shows you only what you have funds on. That is a well-intentioned though misguided approach.

I as a user want to pay with stables in whatever evm chain I have stables and has at the moment lowest fees. All my stables are in various protocol earning yield. Say Aave, compound, curve etc. The payment processor does not detect (and I don't expect it to) stables locked in protocols.

I suggest making it show all possible choices, but maybe just pointing out at the UI if at the moment of selection the user has sufficient funds for the selected payment.

At rotki we do something like that. We use a custom-made payment processing (rudimental) system we made. Looks like this:
![2024-07-16_12-23](https://github.com/user-attachments/assets/d236acd4-fb57-4ae2-9d69-2145f7ce1201)
![2024-07-16_12-23_1](https://github.com/user-attachments/assets/2c5be62c-2704-4623-bd6c-e9fb091c168b)

Also since I want to pay in the next 2 days to get my devcon ticket, and don't want to put pressure on ticket solving is there a place to see all possible payment options for devcon? This way I can "cheat" my way out of the problem by choosing what I want and withdrawing from defi to pay.

**Comment by ryanberckmans** [comment]
Thanks for your submission! Rotki is terrific.

Totally makes sense. A user's "ways to pay" will now be shown all the time after this PR lands is released to production in about 20 minutes.https://github.com/3cities/3cities/pull/152

**Comment by LefterisJP** [comment]
Thanks a lot for solving this so fast! I can confirm it works.

**Comment by ryanberckmans** [comment]
My pleasure! Thanks for the feedback and testing. Cheers
